### ISSUE TITLE
where is test.py mentioned in README?

### ISSUE THREAD

**Issue by LeeSureman** [Alrope123/rethinking-demonstrations#2]

**Comment by shmsw25** [comment]
Its in [the MetaICL repo](https://github.com/facebookresearch/MetaICL). You need to `git clone` (or `git pull`) the MetaICL repo in order to run experiments. Please see the guidelines in the README ([the preparation section](https://github.com/Alrope123/rethinking-demonstrations#preparation)) for details.

**Comment by LeeSureman** [comment]
Very appreciated for your response!
